### ISSUE TITLE
Crash with git repo

### ISSUE THREAD

**Issue by MrMic** [Tharre/st-transparency#2]
Hi,

When I come into a repository with ".git/" repository inside, 
 it crashes.
When I wipe it out, it is OK.
Can u investigate?

Rgds,

PS: Good work anyway and happy new year 2021! ;)

**Comment by Tharre** [comment]
Probably was the emoji crash that was finally fixed:
https://gitlab.freedesktop.org/xorg/lib/libxft/-/blob/libXft-2.3.6/NEWS
